### ISSUE TITLE
Schedule monthly calls

### ISSUE THREAD

**Issue by laura-alagna** [dpscollaborative/btr-planning#18]
During the next phase of the grant, we should have monthly check-in calls on the calendar (even if we cancel them occasionally).

**Comment by laura-alagna** [comment]
https://docs.google.com/forms/d/1_LpLPVjmMIeQXFe8vHsJl2Vzy83IymoJLOHsHy5-onY/edit need replies from @bbranan @diamondap and @thibgc

**Comment by bbranan** [comment]
My reply is in. (It's not clear in the form responses who submitted what, so I figured I'd call it out.)
