### ISSUE TITLE
Review LoC validator code

### ISSUE THREAD

**Issue by laura-alagna** [dpscollaborative/btr-planning#19]
Review the LoC validator code and assess whether it (or some pieces of it) can be adapted for use in updates to DSpace/Fedora and LOCKSS (and perhaps Exactly?)

This is dependent on what the LoC folks have planned for the future (maybe they will be making changes to it soon?)

If a call to discuss the LoC validator would be helpful, ping @laura-alagna to schedule

**Comment by bbranan** [comment]
Copied from slack:

From what I can tell reading through the LoC bagit-java code, the BagProfileChecker is intended to read the JSON file that defines a profile and check that the expected elements defined in the profile are present (https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/conformance/BagProfileChecker.java). This seems like a good starting point for BtR validation needs. I haven't actually executed the code, as there's no CLI, so code would need to be written to execute the classes of interest. Clearly some updates would be needed (the list of checksum algorithms doesn't include SHA-512, for example). But even if the profile-specific components of the library don't turn out to be useful, the base Bag validation code (https://github.com/LibraryOfCongress/bagit-java/blob/master/src/main/java/gov/loc/repository/bagit/verify/BagVerifier.java) which performs validation based on the bagit spec would be a good starting point. It verifies that content in the payload manifests are present and hashes match.

As @diamondap points out, the example bagit profiles that are in the LoC repository are structurally different than the profile we're using. This suggests that more work may be needed to reuse or replace the profile checking code (BagProfileChecker, linked above). Some testing and experimentation will be needed to make that determination. We may choose to only use the BagVerifier component and create our own profile validation code.

**Comment by laura-alagna** [comment]
Thanks, @bbranan. If you haven't had a chance to review the validator code, @thibgc @bertramlyons, if you could take a look before our monthly call next week (Nov 13) that would be great!
