### ISSUE TITLE
Pull request for changes to BagIt Profiles

### ISSUE THREAD

**Issue by laura-alagna** [dpscollaborative/btr-planning#7]
Draft the pull request to the BagIt Profiles readme once the changes have been reviewed by the team (deadline 10/4/2019) and then submit the pull request by mid-October

**Comment by laura-alagna** [comment]
I believe @diamondap has done this, so I am closing this issue

**Comment by diamondap** [comment]
Actually, I did not do the pull request for BtR. I thought that was assigned to someone else. Do you know who this was assigned to?

**Comment by laura-alagna** [comment]
Ah, sorry @diamondap. reopening this...I believe @tdilauro was going to do the pull request. Tim, can you do it? thanks!

**Comment by tdilauro** [comment]
Sure. I'll put a draft together today. I haven't received any feedback on this, so I just requested a couple of reviews and will complete the PR once those reviews are complete.

**Comment by tdilauro** [comment]
[Pull request](https://github.com/bagit-profiles/bagit-profiles/pull/21) submitted. 

Thanks to @bbranan and @diamondap for helping make that happen.
