### ISSUE TITLE
Develop conforming bag examples

### ISSUE THREAD

**Issue by laura-alagna** [dpscollaborative/btr-planning#8]
We need examples of bags that conform to the BtR profile. Create snippets of bags that conform -- these should demonstrate how to use specific fields that are updated/new in BtR. Entire conforming bags can be added as an appendix. 

See the definitions for further information: https://docs.google.com/document/d/1QXLbvEqUS5GGfH7CozcyvX_om8w_xOTH0psmNWCATzM/edit

**Comment by laura-alagna** [comment]
Sample bags here: https://github.com/dpscollaborative/btr_bagit_profile/tree/master/sample_bags
@diamondap does @jhsimpson need to do anything to help with this?

**Comment by diamondap** [comment]
I don't think so, unless he wants to add some samples to test specific use cases.
